# Generated by Django 5.0.6 on 2024-06-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('profile', models.ImageField(null=True, upload_to='profile_images/')),
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('psize', models.IntegerField()),
                ('pheight', models.IntegerField()),
                ('possiblediseases', models.CharField(max_length=200)),
            ],
        ),
    ]
