# Generated by Django 5.0.6 on 2024-06-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='psize',
        ),
        migrations.AddField(
            model_name='plant',
            name='pfamily',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pror',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='psoiltype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
